# Generated by Django 4.1.4 on 2022-12-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0003_kategoria_produkty_kategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='producent',
            options={'verbose_name': 'Producent', 'verbose_name_plural': 'Producenci'},
        ),
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='produkty',
            name='ilosc',
            field=models.IntegerField(default=0),
        ),
    ]
